# Generated by Django 3.1.4 on 2021-03-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
